services:
  nginx:
    image: nginx:1.27.4-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../ChatSync_Application_FE/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db-mysql:
    image: mysql:9.2.0
    restart: always
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

  backend-spring:
    build: 
      context: ./ChatSync_Application_BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - UPLOAD_URI=file:///uploads/
    env_file:
      - ./ChatSync_Application_BE/.env.prod
    depends_on:
      - db-mysql
    volumes:
      - ../uploads:/uploads

  frontend-nextjs:
    build: 
      context: ./ChatSync_Application_FE
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend-spring

volumes:
  db_data: